version: 1.0
runtime: docker
build:
  commands:
    build:
      - echo "Building Book Sales Platform"
      - docker build -t book-sales-api .
      - docker build -t streamlit-dashboard ./streamlit
run:
  runtime-version: latest
  command: docker-compose up
  network:
    port: 8000
  env:
    - name: DB_HOST
      value: ${REDSHIFT_ENDPOINT}
    - name: DB_PORT
      value: ${REDSHIFT_PORT}
    - name: DB_NAME
      value: ${REDSHIFT_DB}
    - name: DB_USER
      value: ${REDSHIFT_USER}
    - name: DB_PASSWORD
      value: ${REDSHIFT_PASSWORD}
    - name: AWS_REGION
      value: ${AWS_REGION}
